# Generated by Django 5.1.7 on 2025-03-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_planteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='poster',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
