# Generated by Django 5.1.7 on 2025-03-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_planteer', '0002_plant_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(default=False, help_text='Check if the plant is edible.'),
        ),
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose the category of the plant.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_planteer.category'),
        ),
    ]
