# Generated by Django 5.1.7 on 2025-03-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0002_alter_plant_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
