# Generated by Django 5.1.7 on 2025-03-10 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_alter_plants_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plants",
            name="category",
            field=models.CharField(
                choices=[
                    ("flower", "Flower"),
                    ("tree", "Tree"),
                    ("vegetable", "Vegetable"),
                    ("fruit", " Fruit"),
                ],
                max_length=250,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=250)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plants.plants"
                    ),
                ),
            ],
        ),
    ]
