# Generated by Django 5.1.7 on 2025-03-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plant_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
