# Generated by Django 5.1.7 on 2025-03-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_rename_requirements_plant_requirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='Requirements',
            new_name='requirements',
        ),
    ]
