# Generated by Django 5.1.7 on 2025-03-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='is_edible',
            field=models.BooleanField(default=True),
        ),
    ]
