# Generated by Django 5.1.7 on 2025-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2010)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('categoy', models.CharField(max_length=2010)),
                ('is_edible', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
