# Generated by Django 5.1.7 on 2025-03-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2010)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(default=True),
        ),
    ]
