# Generated by Django 5.1.7 on 2025-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planteer', '0002_plant_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='types',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
