# Generated by Django 5.1.6 on 2025-03-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('about', models.TextField()),
                ('user_for', models.TextField()),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('category', models.CharField(choices=[('Indoor', 'Indoor Plants'), ('Outdoor', 'Outdoor Plants'), ('Flowering', 'Flowering Plants'), ('Succulents', 'Succulents & Cacti'), ('Herbs', 'Herbs & Medicinal Plants'), ('Trees', 'Trees & Shrubs'), ('Fruit', 'Fruit Plants & Trees'), ('Vegetables', 'Vegetable Plants')], max_length=20)),
                ('is_edible', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
