# Generated by Django 5.1.6 on 2025-03-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Flowering', 'Flowering Plants'), ('Herbs', 'Herbs & Medicinal Plants'), ('Trees', 'Trees & Shrubs'), ('Fruit', 'Fruit Plants & Trees'), ('Vegetables', 'Vegetable Plants')], max_length=20),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
            ],
        ),
    ]
