# Generated by Django 5.1.7 on 2025-03-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='last_name',
        ),
    ]
