# Generated by Django 5.1.7 on 2025-03-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_first_name_contactmessage_full_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
