# Generated by Django 5.1.6 on 2025-03-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_conatct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conatct',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
